### ISSUE TITLE
Docs unclear - in preparing the env. 

### ISSUE THREAD

**Issue by mykaul** [RedHatInsights/insights-core-tutorials#2]
```
Next you need to run the setup_env.sh script to set up your python environment.

(env)[userone@hostone insights-core-tutorials]$ setup_env.py
```

So do you need to run setup_env.sh, or setup_env.py ? Note that there's setup.py in the dir as well as setup_env.sh.

**Comment by mykaul** [comment]
Link - https://insights-core-tutorials.readthedocs.io/en/latest/prep_tutorial_env.html

**Comment by lhuett** [comment]
Thank you for pointing this out Yaniv. This should be corrected now.
